### ISSUE TITLE
Lorem Ipsum in Features

### ISSUE THREAD

**Issue by arey-pranay** [onwidget/tailnext#37]
#### Description

When you visit the website's features section, half of the features have relevant text while the other half has just random lorem ipsum. It should be kept uniform and adding relevant text for all the features seems like a fair solution to it.

#### Screenshot

![image](https://github.com/onwidget/tailnext/assets/86497126/49cd5633-2dc2-4b00-bbd8-7575ccedc806)

#### Steps To Reproduce 

- Go to https://tailnext.vercel.app/
- Scroll Down to the features section

**Comment by prototypa** [comment]
Hi @arey-pranay and thanks for this. Issue fixed by yourself: https://github.com/onwidget/tailnext/pull/38
