### ISSUE TITLE
First click on dark mode button doesn't change theme

### ISSUE THREAD

**Issue by Balhut** [onwidget/tailnext#7]
Hi! 

I've been exploring on integrating NextJS 13 (with new app dir) with TailwindCSS and I've found out your example. It does look great!

I've noticed some strange DarkMode toggle behaviour - if it's your first visit on the page (you can reproduce it by visiting your demo in incognito mode) then first click on the button does not change the theme. It changes the icon, but no the theme itself.

I was wondering if it might be connected with the prerendering NextJS does to Client Side components, so the "theme" state taken from next-themes is affected by this, but I'm not sure. 

Worth noting - I'm on macOS 13.1, system preferences are set to Dark by default and I've been testing with newest Chrome and Firefox browsers.

**Comment by gianpaj** [comment]
it's probably more likely the dark-theme detection doesn't work .it's using `next-themes`

**Comment by prototypa** [comment]
Hi @Balhut 

That issue was already solved some time ago. We missed letting you know.
